// krithikkattyparambil@gmail.com/week 3/hands on 7/course-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  templateUrl: './course-card.component.html',
  styleUrls: ['./course-card.component.css'],
})
export class CourseCardComponent {
  @Input() name = '';
  @Input() code = '';
  @Input() credits = 0;
  @Input() grade = '';
}

<article
  class="course-card"
  tabindex="0"
  (keydown.enter)="$event.target.click()"
>
  <h3>{{ name }}</h3>
  <p>{{ code }}</p>
  <span class="credits">{{ credits }} credits</span>
  <span class="grade" *ngIf="grade">Grade: {{ grade }}</span>
</article>

// krithikkattyparambil@gmail.com/week 3/hands on 5/CourseCard.jsx
export default function CourseCard({ id, name, code, credits, grade, onEnroll }) {
  return (
    <article className="course-card">
      <h3>{name}</h3>
      <p>{code}</p>
      <span className="credits">{credits} credits</span>
      {grade && <span className="grade">Grade: {grade}</span>}
      {onEnroll && (
        <button type="button" onClick={() => onEnroll(id)}>
          Enroll
        </button>
      )}
    </article>
  );
}
