// krithikkattyparambil@gmail.com/week 5/handson 8/Header.vue
<script setup>
import { useEnrollmentStore } from '../stores/enrollment.js';

const store = useEnrollmentStore();
</script>

<template>
  <header class="app-header">
    <div class="site-name">Student Portal</div>
    <nav aria-label="Main navigation">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">Profile</RouterLink>
    </nav>
    <span class="enrolled-badge">Enrolled: {{ store.enrolledCourses.length }}</span>
  </header>
</template>

// krithikkattyparambil@gmail.com/week 3/hands on 5/Header.jsx
export default function Header({ siteName, enrolledCount = 0 }) {
  return (
    <header className="app-header">
      <div className="site-name">{siteName}</div>
      <nav>
        <ul>
          <li><a href="#hero">Home</a></li>
          <li><a href="#courses">Courses</a></li>
          <li><a href="#profile">Profile</a></li>
        </ul>
      </nav>
      <span className="enrolled-badge">Enrolled: {enrolledCount}</span>
    </header>
  );
}
