// krithikkattyparambil@gmail.com/week 5/handson 8/Header.vue
<script setup>
import { useEnrollmentStore } from '../stores/enrollment.js';

const store = useEnrollmentStore();
</script>

<template>
  <header class="app-header">
    <div class="site-name">Student Portal</div>
    <nav aria-label="Main navigation">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">Profile</RouterLink>
    </nav>
    <span class="enrolled-badge">Enrolled: {{ store.enrolledCourses.length }}</span>
  </header>
</template>

// krithikkattyparambil@gmail.com/week 5/handson 6/Header.jsx
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { selectEnrolledCount } from '../store/enrollmentSlice.js';

export default function Header() {
  const enrolledCount = useSelector(selectEnrolledCount);

  return (
    <header className="app-header">
      <div className="site-name">Student Portal</div>
      <nav>
        <ul>
          <li><Link to="/">Home</Link></li>
          <li><Link to="/courses">Courses</Link></li>
          <li><Link to="/profile">Profile</Link></li>
        </ul>
      </nav>
      <span className="enrolled-badge">Enrolled: {enrolledCount}</span>
    </header>
  );
}
